### ISSUE TITLE
tracking the rejected data

### ISSUE THREAD

**Issue by hyunchul386** [UMD-AOSC/OceanObsQC#14]

**Comment by hyunchul386** [comment]
Tracking the rejected data from each checking

**Comment by hyunchul386** [comment]
set a new vector of "profile" type, obs_rej.
put the vector in new argument to SOUBROUTINE qc_step_check.

**Comment by travissluka** [comment]
@hyunchul386  I would like to see this merged into develop first before any of the other qc checks are merged.
I don't think the hour variable should be modified, because we might want to look at the hour to see if that is why data is rejected. I think a new variable should be added to the output with a qc flag.

**Comment by hyunchul386** [comment]
I agree and will put the new variable "tag" in out puts etc.
After that will merge this one into github
